export default [
  { _id: "001",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "002",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "003",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "004",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "005",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "006",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "007",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "008",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "009",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  { _id: "010",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
];