export default [
  { xid: "001",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "002",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "003",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "004",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "005",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "006",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "007",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "008",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "009",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
  { xid: "010",
    image: "image.jpeg",
    name: "Name of Place",
    address: {city: "City", country: "Country",}},
];