export default [
  {id: "001",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "002",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "003",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "004",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "005",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "006",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "007",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "008",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "009",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
  {id: "010",
    image: "image.jpeg",
    title: "Name of Place",
    otherThing: "about content",},
];